class AppString {
  AppString._();
  static const String categoryFood = "food";
  static const String categoryOther = "other";
  static const String categoryClothing = "clothing";
  static const String categoryRent = "rent";
  static const String categoryBike = "bike";
  static const String categoryTransport = "transport";
  static const String categoryUtils = "utils";
  static const String categoryKhaja = "khaja";
  static const String categoryMilk = "milk";
  static const String categoryWater = "water";
  static const String categoryGrocery = "grocery";
  static const String categoryChocolate = "chocolate";
  static const String categoryMeat = "meat";
  static const String categoryStationary = "stationary";
  static const String categoryFruits = "fruits";
  static const String categoryCosmetic = "cosmetic";
  static const String categoryPetrol = "petrol";
  static const String categoryMedicine = "medicine";
  static const String categoryGas = "gas";
  static const String categoryRice = "rice";
  static const String categorySugar = "sugar";
  static const String categoryPersonal = "personal";
  static const String categorySnacks = "snacks";
  static const String categoryShampoo = "shampoo";
  static const String categoryIcecream = "icecream";
  static const String categoryOffice = "office expense";
  static const String categoryJhyapliKhaja = "jhyapli khaja";
  static const String categoryColdDrink = "cold drink";
  static const String categorySubinExpense = "subin expense";
}
